tmayan/Group4Project

src/TC_002.java

Tugba's branch

---

src/TC_004.java

Tugba's second branch

---

src/TC_005.java

those codes just has been updated and needs to be merge

Tc001 code has been completed ,requesting permission to merge

---

src/tugba/tugba.java

tugba job is done..please review

Tugba tc100

---

src/memet/TC500.java

Memet tc500

---

src/shirin/TC001.java

Shirin tc001

---

src/b23Margie/Car.java

B23 margie

---

src/memet/LoginF.java

B23 login option is done

---

src/tugba/login.java

this is pull request opened after setting up branch protection.....

B23 login func is done

---

src/mucahit/TC500.java

initial commit

---

src/b23Margie/LoginFunctionality.java

B23 login 

---

src/tugba/ShowMeChangeRequestButton.java

Tugba new branch

---

src/shirin/Task.java

Shirin task

---

src/tugba/hello.java

Reverts tmayan/Group4Project#22
add more codes

Revert "Tugbas"

---

src/Alexis/newtask.java

adding something extra

---

src/memet/Logout1.java

memet wotk done

---

src/b23Margie/LoginFunctionality.java

Login functionality- abc 

---

src/shirin/LoginFunction.java

done with the login function

---

src/zaur/FridayMorning.java

Happy Friday

---

src/Turgay/TurgayNew.java

I created new branch and new work and is done.

New work is done

---

src/zaur/Review.java

More practice
